# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('temperament', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
